import React, { useState } from 'react';
import { ArrowRight, CalendarDays, CarFront, CheckCircle2, Clock3, MapPin, Menu, MessageCircle, ShieldCheck, Sparkles, Users, X } from 'lucide-react';

const API_BASE = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api').replace(/\/$/, '');
const WHATSAPP_NUMBER = (import.meta.env.VITE_WHATSAPP_NUMBER || '919014726337').replace(/\D/g, '');
const initialForm = { fullName: '', mobileNumber: '', pickupPoint: '', destination: '', dropPoint: '', travelDate: '', travelTime: '', passengers: '1', tripType: 'One Way', notes: '' };

function Brand({ light = false }) {
  return <a className={`brand ${light ? 'brand-light' : ''}`} href="#home" aria-label="Anil Cabs home"><span className="brand-mark"><CarFront size={25} strokeWidth={2.5} /></span><span><strong>ANIL <i>CABS</i></strong><small>SAFE · RELIABLE · COMFORTABLE</small></span></a>;
}

function App() {
  const [form, setForm] = useState(initialForm);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [booking, setBooking] = useState(null);
  const [menuOpen, setMenuOpen] = useState(false);

  const update = (event) => setForm(current => ({ ...current, [event.target.name]: event.target.value }));

  async function submitBooking(event) {
    event.preventDefault(); setError(''); setBooking(null);
    if (!/^\d{10}$/.test(form.mobileNumber)) { setError('Please enter a valid 10-digit Indian mobile number.'); return; }
    if (form.travelDate && form.travelDate < new Date().toLocaleDateString('en-CA')) { setError('Travel date cannot be in the past.'); return; }
    setLoading(true);
    try {
      const response = await fetch(`${API_BASE}/bookings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.message || 'Could not save your booking. Please try again.');
      setBooking(data);
      const message = [
        'Hello Anil Cabs! I would like to book a cab.', '',
        `Booking ID: ${data.bookingCode}`, `Name: ${form.fullName}`, `Mobile: ${form.mobileNumber}`,
        `Trip type: ${form.tripType}`, `Pickup point: ${form.pickupPoint}`, `Destination: ${form.destination}`,
        `Drop point: ${form.dropPoint || form.destination}`, `Date: ${form.travelDate || 'To be confirmed'}`,
        `Time: ${form.travelTime || 'To be confirmed'}`, `Passengers: ${form.passengers}`,
        form.notes ? `Notes: ${form.notes}` : '', '', 'Please confirm availability and fare.'
      ].filter(Boolean).join('\n');
      window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
      setForm(initialForm);
    } catch (e) {
      setError(`${e.message} Make sure the Java backend is running and the API URL is correct.`);
    } finally { setLoading(false); }
  }

  return <div className="app-shell" id="home">
    <div className="top-strip"><div className="container top-strip-inner"><span><Clock3 size={14}/> Available 24/7</span><span className="top-right">Hyderabad, Telangana <span className="dot"/> Your journey, our responsibility</span></div></div>
    <header className="header"><div className="container nav-wrap"><Brand /><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <Menu/>}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a href="#services" onClick={() => setMenuOpen(false)}>Our Services</a><a href="#why-us" onClick={() => setMenuOpen(false)}>Why Anil Cabs</a><a href="#booking" onClick={() => setMenuOpen(false)} className="nav-cta">Book a Cab <ArrowRight size={16}/></a></nav></div></header>

    <main>
      <section className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> YOUR RIDE. YOUR WAY.</div><h1>Every journey<br/>starts with <span>trust.</span></h1><p className="hero-lead">Comfortable rides, reliable service, and easy booking through WhatsApp. Tell us where you want to go — we’ll take it from there.</p><div className="hero-actions"><a href="#booking" className="button button-orange">Book your cab <ArrowRight size={18}/></a><a className="button button-outline" href={`https://wa.me/${WHATSAPP_NUMBER}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Chat on WhatsApp</a></div><div className="hero-trust"><span><ShieldCheck size={17}/> Safe & dependable</span><span><Clock3 size={17}/> 24/7 service</span></div></div>
      <div className="hero-visual"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="visual-card"><div className="visual-card-top"><span className="live-dot"/> READY WHEN YOU ARE</div><div className="car-art"><div className="car-shadow"/><svg viewBox="0 0 560 260" role="img" aria-label="Illustration of a white sedan cab"><defs><linearGradient id="body" x1="0" x2="0.2" y1="0" y2="1"><stop offset="0" stopColor="#fff"/><stop offset="1" stopColor="#cfd4db"/></linearGradient><linearGradient id="glass" x1="0" x2="1"><stop stopColor="#34404c"/><stop offset="1" stopColor="#121820"/></linearGradient></defs><ellipse cx="285" cy="220" rx="220" ry="18" fill="#000" opacity=".13"/><path d="M73 164 L103 124 Q119 112 158 106 L219 52 Q235 37 266 35 L361 37 Q389 39 410 65 L454 117 Q483 125 493 149 L503 185 L489 204 L62 204 L56 184Z" fill="url(#body)" stroke="#aab2bb" strokeWidth="2"/><path d="M130 118 L228 57 Q240 49 265 49 L300 50 L281 118Z" fill="url(#glass)"/><path d="M292 50 L356 51 Q376 52 391 71 L425 118 L291 118Z" fill="url(#glass)"/><path d="M227 58 L209 118" stroke="#88929d" strokeWidth="4"/><path d="M287 49 L284 119" stroke="#89939d" strokeWidth="4"/><path d="M104 130 Q132 120 156 121 L423 124" fill="none" stroke="#fff" strokeWidth="4" opacity=".8"/><path d="M68 164 L96 158 L102 178 L66 181Z" fill="#fff4d8" stroke="#aeb5bd"/><path d="M461 147 L491 154 L495 170 L466 166Z" fill="#ff7b35"/><path d="M104 180 L453 180" stroke="#9ba4ae" strokeWidth="3"/><path d="M170 130 L171 164 M440 130 L442 164" stroke="#9ba4ae" strokeWidth="3"/><rect x="294" y="143" width="70" height="21" rx="4" fill="#f56a0b"/><text x="329" y="157" fontSize="11" fontWeight="800" fill="#fff" textAnchor="middle">ANIL CABS</text><circle cx="151" cy="194" r="35" fill="#1b2027"/><circle cx="151" cy="194" r="23" fill="#aeb6c0"/><circle cx="151" cy="194" r="14" fill="#333b45"/><circle cx="151" cy="194" r="5" fill="#e7ebef"/><circle cx="426" cy="194" r="35" fill="#1b2027"/><circle cx="426" cy="194" r="23" fill="#aeb6c0"/><circle cx="426" cy="194" r="14" fill="#333b45"/><circle cx="426" cy="194" r="5" fill="#e7ebef"/></svg></div><div className="visual-route"><div className="route-pin"><MapPin size={17}/></div><div><strong>Your destination awaits</strong><small>Pickup to drop-off, made simple</small></div><span className="route-arrow"><ArrowRight size={18}/></span></div></div><div className="floating-badge"><span className="badge-icon"><MessageCircle size={20}/></span><span><strong>Easy booking</strong><small>Right on WhatsApp</small></span></div></div></div></section>

      <section className="booking-section" id="booking"><div className="container booking-layout"><div className="booking-intro"><div className="eyebrow"><span className="eyebrow-line"/> LET’S GET YOU MOVING</div><h2>Book your ride<br/>in <span>just a few steps.</span></h2><p>Share your trip details below. We’ll create a unique booking ID and open WhatsApp with your details ready to send.</p><div className="booking-note"><div className="note-icon"><MessageCircle size={22}/></div><div><strong>WhatsApp-powered booking</strong><p>No app installation needed. Send your booking details directly to our team.</p></div></div><div className="mini-stat-row"><div><strong>24/7</strong><span>Support</span></div><div><strong>1 unique ID</strong><span>For every booking</span></div><div><strong>Simple</strong><span>Booking process</span></div></div></div>
      <div className="form-card"><div className="form-heading"><div><span className="form-step">BOOKING REQUEST</span><h3>Plan your trip</h3></div><span className="form-car-icon"><CarFront size={25}/></span></div>
      {booking && <div className="success-box"><CheckCircle2 size={20}/><div><strong>Booking saved successfully!</strong><span>Your unique booking ID is <b>{booking.bookingCode}</b>. WhatsApp should open in a new tab so you can send the request.</span></div><button onClick={() => setBooking(null)} aria-label="Dismiss"><X size={16}/></button></div>}
      {error && <div className="error-box" role="alert">{error}</div>}
      <form onSubmit={submitBooking} className="booking-form"><div className="form-grid"><label className="field full"><span>Full name <b>*</b></span><input name="fullName" value={form.fullName} onChange={update} placeholder="Enter your full name" autoComplete="name" required maxLength="100"/></label><label className="field"><span>Mobile number <b>*</b></span><div className="input-with-prefix"><span>+91</span><input name="mobileNumber" value={form.mobileNumber} onChange={update} placeholder="10-digit number" inputMode="numeric" pattern="[0-9]{10}" maxLength="10" autoComplete="tel-national" required/></div></label><label className="field"><span>Trip type</span><select name="tripType" value={form.tripType} onChange={update}><option>One Way</option><option>Round Trip</option><option>Local Trips</option><option>Airport Pickup & Drop</option></select></label><label className="field full"><span>Pickup point <b>*</b></span><div className="input-with-icon"><MapPin size={17}/><input name="pickupPoint" value={form.pickupPoint} onChange={update} placeholder="Where should we pick you up?" required maxLength="250"/></div></label><label className="field full"><span>Destination <b>*</b></span><div className="input-with-icon"><MapPin size={17}/><input name="destination" value={form.destination} onChange={update} placeholder="Where are you travelling to?" required maxLength="250"/></div></label><label className="field full"><span>Drop point <small>(if different from destination)</small></span><div className="input-with-icon"><MapPin size={17}/><input name="dropPoint" value={form.dropPoint} onChange={update} placeholder="Final drop location (optional)" maxLength="250"/></div></label><label className="field"><span>Travel date</span><div className="input-with-icon"><CalendarDays size={17}/><input type="date" name="travelDate" value={form.travelDate} onChange={update} min={new Date().toLocaleDateString('en-CA')}/></div></label><label className="field"><span>Pickup time</span><div className="input-with-icon"><Clock3 size={17}/><input type="time" name="travelTime" value={form.travelTime} onChange={update}/></div></label><label className="field"><span>Passengers</span><select name="passengers" value={form.passengers} onChange={update}>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n} {n===1?'passenger':'passengers'}</option>)}</select></label><label className="field full"><span>Additional requests <small>(optional)</small></span><textarea name="notes" value={form.notes} onChange={update} placeholder="Luggage, return trip details, or anything we should know" rows="2" maxLength="500"/></label></div>
      <button className="button button-orange submit-button" type="submit" disabled={loading}>{loading ? <><span className="spinner"/> Saving booking...</> : <>Save booking & continue to WhatsApp <ArrowRight size={18}/></>}</button><p className="form-privacy"><ShieldCheck size={14}/> Your details are used to coordinate this booking.</p></form></div></div></section>

      <section className="services-section" id="services"><div className="container"><div className="section-heading"><div className="eyebrow"><span className="eyebrow-line"/> WHEREVER YOU NEED TO GO</div><h2>One ride away from <span>anywhere.</span></h2><p>Flexible cab services for everyday travel and special journeys.</p></div><div className="service-grid"><article className="service-card"><div className="service-icon"><CarFront/></div><h3>Airport Pickup & Drop</h3><p>Start or finish your flight journey with a planned, convenient ride.</p><a href="#booking">Book airport ride <ArrowRight size={15}/></a></article><article className="service-card"><div className="service-icon"><MapPin/></div><h3>Local Trips</h3><p>Travel around Hyderabad for appointments, shopping, and daily plans.</p><a href="#booking">Book local ride <ArrowRight size={15}/></a></article><article className="service-card"><div className="service-icon"><CalendarDays/></div><h3>Outstation & Packages</h3><p>Plan one-way, round-trip, and monthly travel requirements.</p><a href="#booking">Plan a trip <ArrowRight size={15}/></a></article></div></div></section>

      <section className="why-section" id="why-us"><div className="container why-grid"><div><div className="eyebrow eyebrow-light"><span className="eyebrow-line"/> THE ANIL CABS PROMISE</div><h2>Travel easy.<br/><span>Travel confidently.</span></h2><p>We keep the booking process simple, so you can focus on your journey. Share your trip details, receive your unique booking reference, and coordinate with us on WhatsApp.</p><a href="#booking" className="button button-orange">Start a booking <ArrowRight size={18}/></a></div><div className="promise-list"><div className="promise-item"><span><ShieldCheck/></span><div><strong>Safety comes first</strong><p>Trip details are recorded so your request can be tracked.</p></div></div><div className="promise-item"><span><MessageCircle/></span><div><strong>Direct WhatsApp coordination</strong><p>Review your trip details before sending them to our team.</p></div></div><div className="promise-item"><span><Sparkles/></span><div><strong>A unique ID for every booking</strong><p>Use your booking reference when asking about your trip.</p></div></div><div className="promise-item"><span><Users/></span><div><strong>Built around your plans</strong><p>Provide your route, schedule, and passenger count in one form.</p></div></div></div></div></section>

      <section className="final-cta"><div className="container final-cta-inner"><div><span>READY FOR YOUR NEXT JOURNEY?</span><h2>Your journey, our responsibility.</h2></div><a href="#booking" className="button button-dark">Book Anil Cabs <ArrowRight size={18}/></a></div></section>
    </main>
    <footer className="footer"><div className="container footer-main"><Brand light/><div className="footer-contact"><span><MapPin size={16}/> Hyderabad, Telangana</span><a href={`https://wa.me/${WHATSAPP_NUMBER}`} target="_blank" rel="noreferrer"><MessageCircle size={16}/> WhatsApp Anil Cabs</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Anil Cabs. All rights reserved.</span><span>Safe · Reliable · Comfortable</span></div></footer>
  </div>;
}

export default App;
